### ISSUE TITLE
Rendering Wither crashes the game

### ISSUE THREAD

**Issue by turtletowerz** [Legacy-Fabric/fabric-loader-1.8.9#1]
Happens with fabric-1.8.9 version 0.8.2+build.202004210808. When attempting to join multiplayer servers with the Wither spawned in (eg. Hypixel or Mineplex), the client immediately crashes. Spawning a Wither in singleplayer will also crash it. The stack trace for the crash report can be found below

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/9/20 9:09 PM
Description: Rendering entity in world

java.lang.AbstractMethodError: net.minecraft.class_1880.f_()Lnet/minecraft/class_1444;
	at net.minecraft.class_1001.method_3301(class_1001.java:15)
	at net.minecraft.class_1179.method_4073(class_1179.java:23)
	at net.minecraft.class_1179.method_3910(class_1179.java:11)
	at net.minecraft.class_1135.method_3891(class_1135.java:295)
	at net.minecraft.class_1135.method_3893(class_1135.java:260)
	at net.minecraft.class_1135.method_3892(class_1135.java:227)
	at net.minecraft.class_1036.method_3527(class_1036.java:596)
	at net.minecraft.class_1012.method_3359(class_1012.java:1244)
	at net.minecraft.class_1012.method_3369(class_1012.java:1149)
	at net.minecraft.class_1012.method_3356(class_1012.java:1002)
	at net.minecraft.class_669.method_2286(class_669.java:915)
	at net.minecraft.class_669.method_2247(class_669.java:325)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.class_1001.method_3301(class_1001.java:15)
	at net.minecraft.class_1179.method_4073(class_1179.java:23)
	at net.minecraft.class_1179.method_3910(class_1179.java:11)

-- Entity being rendered --
Details:
	Entity Type: WitherBoss (net.minecraft.class_1880)
	Entity ID: -1234
	Entity Name: §9§lSKYBLOCK TONS OF UPDATES - LIVE
	Entity's Exact location: 8.03, 70.00, -0.53
	Entity's Block location: 8.00,70.00,-1.00 - World: (8,70,-1), Chunk: (at 8,4,15 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1179@3b60be3
	Location: 32.99,0.00,-0.00 - World: (32,0,-1), Chunk: (at 0,0,15 in 2,-1; contains blocks 32,0,-16 to 47,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 0.0
	Delta: 0.550724
Stacktrace:
	at net.minecraft.class_1135.method_3891(class_1135.java:295)
	at net.minecraft.class_1135.method_3893(class_1135.java:260)
	at net.minecraft.class_1135.method_3892(class_1135.java:227)
	at net.minecraft.class_1036.method_3527(class_1036.java:596)
	at net.minecraft.class_1012.method_3359(class_1012.java:1244)
	at net.minecraft.class_1012.method_3369(class_1012.java:1149)

```

**Comment by hYdos** [comment]
have you tested this in vanilla 1.8.9? what mods are you using?

**Comment by turtletowerz** [comment]
Vanilla 1.8.9 works fine and no mods are installed.
